[package]
name = "markdown"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen-guest-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", rev="d24b97f" }
pulldown-cmark = { version = "0.9.2", default-features = false }
